version: '3'

services:
  php-5.5:
    build:
      context: ./php-5.5
    image: 'datadog/dd-trace-ci:php-5.5_centos-6'

  php-8.0:
    build:
      context: ./php-8.0
      args:
        phpVersion: 8.0
        phpTarGzUrl: https://downloads.php.net/~pollita/php-8.0.0RC2.tar.gz
        phpSha256Hash: 0cebc11c61c0f153bd866eab76c424404b3ccc779417cdfde1061e550c3e364c
    image: 'datadog/dd-trace-ci:php-8.0_centos-6'
