version: '3'

services:
  php-5.5:
    build:
      context: ./php-5.5
    image: 'datadog/dd-trace-ci:php-5.5_centos-6'

  php-8.0:
    build:
      context: ./php-8.0
      args:
        phpVersion: 8.0
        phpTarGzUrl: https://github.com/php/php-src/archive/php-8.0.0RC5.tar.gz
        phpSha256Hash: ec5836f816e17fd8a281f671bb247b4c420f8de23fb425d599877cd911a54230
    image: 'datadog/dd-trace-ci:php-8.0_centos-6'
