version: '3.7'

services:

  base:
    image: datadog/dd-trace-ci:buster
    build:
      context: .

  php-8.0:
    image: datadog/dd-trace-ci:php-8.0_buster
    build:
      context: ./php-8.0
      args:
        phpVersion: 8.0
        phpTarGzUrl: https://downloads.php.net/~carusogabriel/php-8.0.0RC3.tar.gz
        phpSha256Hash: c651a10058840abd44f99a8aed0446f102291d1408f2299790b919634689b5cd

  php-master:
    image: datadog/dd-trace-ci:php-master_buster
    build:
      context: ./php-master
