version: '3.7'

services:

  7.3-alpine:
    image: datadog/dd-trace-ci:php-compile-extension-alpine-7.3
    build:
      context: .
      dockerfile: Dockerfile_alpine
      args:
        php_version: 7.3.2
        php_sha: 010b868b4456644ae227d05ad236c8b0a1f57dc6320e7e5ad75e86c5baf0a9a8
        php_api: 20180731
    command: build-dd-trace-php
    volumes:
        - ../../:/app

  5.6-alpine:
    image: datadog/dd-trace-ci:php-compile-extension-alpine-5.6
    build:
      context: .
      dockerfile: Dockerfile_alpine
      args:
        php_version: 5.6.40
        php_sha: 1369a51eee3995d7fbd1c5342e5cc917760e276d561595b6052b21ace2656d1c
        php_api: 20131106
    command: build-dd-trace-php
    volumes:
        - ../../:/app
