version: '3.7'

services:

  5.5-alpine:
    image: datadog/dd-trace-ci:php-compile-extension-alpine-5.5
    build:
      context: .
      dockerfile: Dockerfile_alpine
      args:
        php_version: 5.5.38
        php_sha: cb527c44b48343c8557fe2446464ff1d4695155a95601083e5d1f175df95580f
        php_api: 20121113
    command: build-dd-trace-php
    volumes:
        - ../../:/app

  5.6-alpine:
    image: datadog/dd-trace-ci:php-compile-extension-alpine-5.6
    build:
      context: .
      dockerfile: Dockerfile_alpine
      args:
        php_version: 5.6.40
        php_sha: 1369a51eee3995d7fbd1c5342e5cc917760e276d561595b6052b21ace2656d1c
        php_api: 20131106
    command: build-dd-trace-php
    volumes:
        - ../../:/app

  7.0-alpine:
    image: datadog/dd-trace-ci:php-compile-extension-alpine-7.0
    build:
      context: .
      dockerfile: Dockerfile_alpine
      args:
        php_version: 7.0.33
        php_sha: ab8c5be6e32b1f8d032909dedaaaa4bbb1a209e519abb01a52ce3914f9a13d96
        php_api: 20151012
    command: build-dd-trace-php
    volumes:
        - ../../:/app

  7.1-alpine:
    image: datadog/dd-trace-ci:php-compile-extension-alpine-7.1
    build:
      context: .
      dockerfile: Dockerfile_alpine
      args:
        php_version: 7.1.33
        php_sha: bd7c0a9bd5433289ee01fd440af3715309faf583f75832b64fe169c100d52968
        php_api: 20160303
    command: build-dd-trace-php
    volumes:
        - ../../:/app

  7.2-alpine:
    image: datadog/dd-trace-ci:php-compile-extension-alpine-7.2
    build:
      context: .
      dockerfile: Dockerfile_alpine
      args:
        php_version: 7.2.34
        php_sha: 409e11bc6a2c18707dfc44bc61c820ddfd81e17481470f3405ee7822d8379903
        php_api: 20170718
    command: build-dd-trace-php
    volumes:
        - ../../:/app

  7.3-alpine:
    image: datadog/dd-trace-ci:php-compile-extension-alpine-7.3
    build:
      context: .
      dockerfile: Dockerfile_alpine
      args:
        php_version: 7.3.23
        php_sha: 2bdd36176f318f451fb3942bf1e935aabb3c2786cac41a9080f084ad6390e034
        php_api: 20180731
    command: build-dd-trace-php
    volumes:
        - ../../:/app

  7.4-alpine:
    image: datadog/dd-trace-ci:php-compile-extension-alpine-7.4
    build:
      context: .
      dockerfile: Dockerfile_alpine
      args:
        php_version: 7.4.11
        php_sha: 5d31675a9b9c21b5bd03389418218c30b26558246870caba8eb54f5856e2d6ce
        php_api: 20190902
    command: build-dd-trace-php
    volumes:
        - ../../:/app
