version: '3.7'

services:

  script:
    build:
      context: .
    volumes:
      - ./:/app
    depends_on:
      - httpbin
      - agent

  httpbin:
    image: kennethreitz/httpbin

  agent:
    image: datadog/agent:latest
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /proc/:/host/proc/:ro
    - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
    - DD_API_KEY=${DATADOG_API_KEY}
