name: Check snapshots

on:
  - push # TODO: Change to 'pull_request' when the action is ready

jobs:
  check-snapshots:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.101'

      - name: "Check Snapshots"
        run: dotnet run --project ./../dotnet/project.csproj --target SummaryOfSnapshotChanges
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PullRequestNumber: "${{ github.event.pull_request.number }}"
          TargetBranch: "${{ github.base_ref }}"
