name: system-tests

on:
  workflow_run:
    workflows: ["Package"]
    types:
      - completed
    branches: [ master ]
  workflow_dispatch:

jobs:
  system-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - weblog-variant: apache-mod
          - weblog-variant: php-fpm
    env:
      TEST_LIBRARY: php
      WEBLOG_VARIANT: ${{ matrix.weblog-variant }}
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
    steps:
      - name: Checkout system tests
        uses: actions/checkout@v2
        with:
          repository: 'DataDog/system-tests'

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: package.yml
          workflow_conclusion: success
          name: package
          path: binaries/

      - name: Remove debug package
        run: |
          ls -la binaries/
          rm binaries/*debug.tar.gz

      - name: Build
        run: ./build.sh

      - name: Run
        run: ./run.sh

      - name: Compress artifact
        if: ${{ always() }}
        run: tar -czvf artifact.tar.gz $(ls | grep logs)

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: logs_${{ matrix.weblog-variant }}
          path: artifact.tar.gz

